-- Generated by merise_dot

drop database mgraph;

create database mgraph;

create table e_0 (
    pk_e_0 int primary key not null
);

create table e_1 (
    pk_e_1 int primary key not null,
    fk_e_2 int
);

create table e_2 (
    pk_e_2 int primary key not null,
    fk_e_1 int not null
);

create table e_3 (
    pk_e_3 int primary key not null
);

create table e_4 (
    pk_e_4 int primary key not null
);

create table lk_e_2_e_3 (
    fk_e_2 int not null,
    fk_e_3 int not null
);

alter table lk_e2_e3
    add constraint unq_lk_e2_e3
        unique (fk_e_2, fk_e_3);

alter table e_1
    add constraint fk_e_1_e_2
        foreign key(fk_e_2)
        references e_2.pk_e_2;

alter table e_2
    add constraint fk_e_2_e_1
        foreign key(fk_e_1)
        references e_1.pk_e_1;

alter table lk_e_2_e_3
    add constraint fk_lk_e2_e3_e_2
        foreign key(fk_e_2)
        references e_2.pk_e_2;

alter table lk_e_2_e_3
    add constraint fk_lk_e2_e3_e_3
        foreign key(fk_e_3)
        references e_3.pk_e_3;

-- vim: ft=mysql
