-- Generated by merise_dot

drop database t2;

create database t2;

create table e_0 (
    pk_e_0 int primary key not null
);

create table e_1 (
    pk_e_1 int primary key not null
);

create table e_2 (
    pk_e_2 int primary key not null
);

create table e_3 (
    pk_e_3 int primary key not null
);

create table e_4 (
    pk_e_4 int primary key not null
);

create table e_5 (
    pk_e_5 int primary key not null
);

create table e_6 (
    pk_e_6 int primary key not null
);

create table e_7 (
    pk_e_7 int primary key not null
);

create table e_8 (
    pk_e_8 int primary key not null
);

create table e_9 (
    pk_e_9 int primary key not null
);

-- vim: ft=mysql
