-- Generated by merise_dot

drop database test;

create database test;

create table e_0 (
    pk_e_0 int primary key not null
);

create table e_1 (
    pk_e_1 int primary key not null
);

create table e_2 (
    pk_e_2 int primary key not null
);

create table e_3 (
    pk_e_3 int primary key not null
);

create table e_4 (
    pk_e_4 int primary key not null
);

-- vim: ft=mysql
